### ISSUE TITLE
Can we have other OS running?

### ISSUE THREAD

**Issue by bien2004official** [c9ffin/rdp#10]
Ex: Ubuntu, android-x86, etc
I want to compile my projects using Android build environment, but WSL2 sucks and doesn't want to run. It took me two hours just to set the correct environment, free over 100GB from Windows partition, just to find out that WSL2 doesn't work with build environment.

Error logs in WSL2 (if you want):

> FAILED: ninja: ./build/blueprint/bootstrap/build.ninja:11: loading 'out/soong/.minibootstrap/build-globs.ninja': Exec format error
> subninja ${myGlobs}
>                    ^ near here
> 06:49:30 soong minibootstrap failed with: exit status 1
> 
> #### failed to build some targets (23 seconds) ####

**Comment by Itroublve** [comment]
No you can't. GitHub Actions only runs Windows Version of Azure, which is limited to 6h.

**Comment by freedom-sys3810** [comment]
> Tidak, kamu tidak bisa. Tindakan GitHub hanya menjalankan Azure Versi Windows, yang dibatasi hingga 6 jam.

Different OS alviabe at https://github.com/RealKoolisw/VirtualMachine-GithubAction
or check my profile, I forked this github.

**Comment by freedom-sys3810** [comment]
> No you can't. GitHub Actions only runs Windows Version of Azure, which is limited to 6h.

Different OS aviable at https://github.com/RealKoolisw/VirtualMachine-GithubAction
or check my profile, I forked this github.

**Comment by Itroublve** [comment]
> > No you can't. GitHub Actions only runs Windows Version of Azure, which is limited to 6h.
> 
> Different OS aviable at https://github.com/RealKoolisw/VirtualMachine-GithubAction
> or check my profile, I forked this github.

Oh this is interesting, thank you for letting me know.
