### ISSUE TITLE
other OS available

### ISSUE THREAD

**Issue by VenomFate-619** [c9ffin/rdp#13]
other OS available rather than windows like Linux ubuntu

**Comment by Itroublve** [comment]
No you can't. GitHub Actions only runs Windows Version of Azure, which is limited to 6h.

**Comment by freedom-sys3810** [comment]
OS lain tersedia di https://github.com/RealKoolisw/VirtualMachine-GithubAction

**Comment by freedom-sys3810** [comment]
Differebt OS alviabe at https://github.com/RealKoolisw/VirtualMachine-GithubAction
or check my profile, I forked this github.

**Comment by freedom-sys3810** [comment]
> Tidak, kamu tidak bisa. Tindakan GitHub hanya menjalankan Azure Versi Windows, yang dibatasi hingga 6 jam.

Differebt OS alviabe at https://github.com/RealKoolisw/VirtualMachine-GithubAction
or check my profile, I forked this github.

**Comment by freedom-sys3810** [comment]
> No you can't. GitHub Actions only runs Windows Version of Azure, which is limited to 6h.

Different OS aviable at https://github.com/RealKoolisw/VirtualMachine-GithubAction
or check my profile, I forked this github.
